image: ubuntu:24.04

before_script :
  - echo "Installing required packages...this can take several minutes"
  - TZ=Europe/Berlin
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  - apt update
  - apt install -y curl
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - source /root/.local/bin/env
  - uv python pin 3.13
  - uv sync --extra torch-cpu --extra flax-cpu
  - uv tool install ruff

stages:  
  - code quality
  - type checking
  - test

ruff:  
  stage : code quality  
  script :
    - echo "Checking code quality..."
    - uvx ruff check src/

mypy:
  stage : type checking
  allow_failure : true
  script :
    - echo "Start static type checking..."
    - uv run mypy src/cobel/ 

demo-job :
  stage : test
  script :
    - echo "Running tests...This will take several minutes"
    - uv pip uninstall flax
    - uv run unit_tests/test_torchnetwork.py
    - uv run unit_tests/test_flexibletorchnetwork.py
