image: ubuntu:22.04

before_script :
  - echo "Installing required packages...this can take several minutes"
  - TZ=Europe/Berlin
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  - apt update
  - apt install -y python3-pip python3-pyqt5 libglib2.0-0 libgl1-mesa-glx qtbase5-dev
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install .
  - pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
  - pip install /tensorflow_pkgs/tensorflow-2.14.1-cp310-cp310-linux_x86_64.whl
  #- pip install tensorflow

stages:  
  - code quality        
  - test

pylint:  
  stage : code quality  
  script :
    - pip install pylint
    - pip install pylint-exit 
    - echo "Checking code quality..."
    - pylint -d C0301 cobel/agents/*.py || pylint-exit $?
    - pylint -d C0301 cobel/frontends/*.py || pylint-exit $?
    - pylint -d C0301 cobel/interfaces/*.py || pylint-exit $?
    - pylint -d C0301 cobel/memory_modules/*.py || pylint-exit $?
    - pylint -d C0301 cobel/spatial_representations/*.py || pylint-exit $?


demo-job :
  stage : test
  script :
    - echo "Running tests...This will take several minutes"
    - python3 unit_tests/test_torchnetwork.py
    - python3 unit_tests/test_flexibletorchnetwork.py
    - python3 unit_tests/test_tensorflow.py
