image: ubuntu:20.04

before_script :
  - echo "Installing required packages...this can take several minutes"
  - apt update
  - apt install python3-pip -y
  - pip3 install --upgrade pip
  - pip3 install virtualenv
  - virtualenv cobel_venv
  - source cobel_venv/bin/activate
  - pip3 install -r requirements.txt
  - pip3 install .
  - TZ=Europe/Berlin
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  - apt-get install libglib2.0-0 -y
  - apt install libgl1-mesa-glx -y

stages:  
  - code quality        
  - test

pylint:  
  stage : code quality  
  script :
    - pip install pylint
    - pip install pylint-exit 
    - echo "Checking code quality..."
    - pylint -d C0301 cobel/agents/*.py || pylint-exit $?
    - pylint -d C0301 cobel/frontends/*.py || pylint-exit $?
    - pylint -d C0301 cobel/interfaces/*.py || pylint-exit $?
    - pylint -d C0301 cobel/memory_modules/*.py || pylint-exit $?
    - pylint -d C0301 cobel/spatial_representations/*.py || pylint-exit $?

demo-job :
  stage : test
  script :
    - echo "Running demos...This will take several minutes"
    - cp -R /builds/cns/1-frameworks/CoBeL-RL /builds/cobel
    - export PYTHONPATH="${PYTHONPATH}:/builds"
    - python -c "import sys;print(sys.path)"
    - pip uninstall tensorflow -y
    - python3 unit_tests/gridworld_pma_test.py